implement 2021 social insurance changes
iza-institute-of-labor-economics/gettsim pull request #253
Opened 2020-12-20 20:18 UTC by Eric-Sommer

- Higher average contribution rate for statutory health insurance
- Higher Assessment ceilings
- Update of pension-relevant parameters
- correct one typo

2020-12-21 11:54 UTC, mjbloemer requested changes
I suggest a few minor reference style changes.

2020-12-21 11:54 UTC, mjbloemer commented on gettsim/parameters/ges_renten_vers.yaml
> +    reference: https://www.bundesregierung.de/breg-de/aktuelles/beitragsbemessungsgrenzen-2021-1796480
suggestion:

```
2018-01-01:
  scalar: 38212
  reference: V. v. 17.12.2019 BGBl. I S. 2848.
2019-01-01:
  scalar: 39301
  reference: V. v. 30.11.2020 BGBl. I S. 2612.
2020-01-01:
  scalar: 40551
  reference: V. v. 17.12.2019 BGBl. I S. 2848.
  note: Das vorläufige Durchschnittsentgelt.
2021-01-01:
  scalar: 41541
  reference: V. v. 30.11.2020 BGBl. I S. 2612.
  note: Das vorläufige Durchschnittsentgelt.
```

2020-12-21 11:54 UTC, mjbloemer commented on gettsim/parameters/soz_vers_beitr.yaml
> +    note: §3, §4 Sozialversicherungs-Rechengrößenverordnung 2021, V. v. 30.11.2020, BGBl. I S. 2612
```suggestion
    reference: V. v. 30.11.2020 BGBl. I S. 2612.
```

2020-12-21 11:54 UTC, mjbloemer commented on gettsim/parameters/soz_vers_beitr.yaml
> +    note: §2 Sozialversicherungs-Rechengrößenverordnung 2021, V. v. 30.11.2020, BGBl. I S. 2612
```suggestion
    reference: V. v. 30.11.2020 BGBl. I S. 2612.
```

2020-12-21 17:05 UTC, Eric-Sommer commented on gettsim/parameters/soz_vers_beitr.yaml
> +    note: §2 Sozialversicherungs-Rechengrößenverordnung 2021, V. v. 30.11.2020, BGBl. I S. 2612
OK. I left the `§2` in, though.

2020-12-31 13:10 UTC, mjbloemer requested changes

2020-12-31 13:10 UTC, mjbloemer commented on gettsim/parameters/ges_renten_vers.yaml
> +   reference: V. v. 17.12.2019 BGBl. I S. 2848.
still incorrect indentation?

2021-01-01 10:15 UTC, Eric-Sommer commented on gettsim/parameters/ges_renten_vers.yaml
> +   reference: V. v. 17.12.2019 BGBl. I S. 2848.
corrected now...frohes neues ;)

2021-01-02 11:47 UTC, mjbloemer approved these changes

2021-01-19 08:20 UTC, merged