Mehrbedarf G
iza-institute-of-labor-economics/gettsim pull request #310
Opened 2021-11-12 17:18 UTC by paulinaschroeder

### What problem do you want to solve?

Add Mehrbedarf G - a Mehrbedarf for people with disabilities which are getting Grundsicherung im Alter und bei Erwerbsminderung - to the implementation of Grundsicherung im Alter

### Todo

- [x] add parameters for rate and threshold
- [x] add function for Mehrbedarf G
- [x] add function to aggregate on household level
- [x] implement in functions for grundsicherung

2021-11-16 11:16 UTC, ChristianZimpelmann requested changes
Thank you @paulinaschroeder, good job!

- I would take out the Einrichtungen. If we go this route, we needed to introduce a new input variable and include it in other files, as well. But can you please open an issue about this? You can also post your code there, such that we can reuse it once we address the issue.
- Please also add your contribution to the file `CHANGES.rst`
- We should also have a few tests for this Mehrbedarf. I would suggest duplicating the last line of `test_dfs_grunds_im_alter.csv` and adjusting those new lines such that they test for a couple of degrees of disability (we might have to add a new column `behinderungsgrad` to this test-data, too. Then make sure that tests are still running through.

2021-11-16 11:16 UTC, ChristianZimpelmann commented on gettsim/parameters/ges_renten_vers.yaml
> +    lower_threshold: 50
Is there really a clear cutoff? In the laws I find different threshold for different types of handicaps.

2022-01-05 07:34 UTC, ChristianZimpelmann requested changes
Tests are running through now! 

Everything looks fine from my side with just one comment for @LauraGergeleit left.

Is there anything else from your perspective, @LauraGergeleit @paulinaschroeder?

2022-01-05 07:34 UTC, ChristianZimpelmann commented on gettsim/parameters/grunds_ia.yaml
> +  description:
@LauraGergeleit, can you improve the documentation of this parameter in a similar fashion as you did for the other retirement parameters?

2022-01-07 12:29 UTC, paulinaschroeder commented
> Is there anything else from your perspective, @LauraGergeleit @paulinaschroeder? Otherwise, we should be able to merge it soon.

I just fixed a calculation error in the test data. Otherwise everything looks good to me

2022-01-10 12:50 UTC, ChristianZimpelmann approved these changes

2022-01-10 12:50 UTC, merged