Update eink_st_abzuege.yaml
iza-institute-of-labor-economics/gettsim pull request #327
Opened 2022-01-11 10:00 UTC by lillyfischer

At the moment, the parameters `behinderten_pauschbetrag` in `eink_st_abzuege.yaml`  start at the 01-01-1987. In fact, these values are also valid for the period 1984-1986 (see https://offenegesetze.de/veroeffentlichung/bgbl1/1984/5?q=einkommensteuergesetz#page=1). 

This pull request changes the starting date of `behinderten_pauschbetrag` from 01-01-1987 to 01-01-1984.

2022-01-11 10:29 UTC, mjbloemer requested changes
Thanks! I also see no reason for dating it to 1987.

Could you add a reference too? For GETTSIM we should use the first date for this set of parameters. I randomly browsed for "Neufassungen" and found that these values are valid in [1981](https://offenegesetze.de/veroeffentlichung/bgbl1/1981/52#page=39) and  [1977](https://offenegesetze.de/veroeffentlichung/bgbl1/1977/81#page=41) too. Do you find the law that changed these parameters to these values? I assume these values were smaller at some point (see e.g. those parameters for [Lohnsteuer in 1960](https://offenegesetze.de/veroeffentlichung/bgbl1/1960/1#page=1)).

2022-01-11 10:58 UTC, ChristianZimpelmann requested changes
Thank you, @lillyfischer! Congrats to opening your first PR 🎉

I would assume there are also some other parameters for which the start date is earlier than specified in the code. But it is good to change it when we see it.

> Do you find the law that changed these parameters to these values?

I agree that when we change it, we should change it to the correct date and preferrably add the respective law that introduced it.

And a final request: Don't forget to mention your contribution in the file `changes.rst` (in the same fashion as the other bullet points there.)

2022-01-12 22:01 UTC, Eric-Sommer commented
It hasn't been there in 1969: https://offenegesetze.de/veroeffentlichung/bgbl1/1969/130?q=Neufassung%20des%20Einkommensteuergesetzes#page=1

2022-01-13 11:02 UTC, mjbloemer commented
I think it is this one: [G. v. 05.08.1974 BGBl. I S. 1769](https://offenegesetze.de/veroeffentlichung/bgbl1/1974/89#page=1). (Gesetz zur Reform der Einkommensteuer, des Familienlastenausgleichs und der Sparförderung (Einkommensteuerreformgesetz - EStRG))

2022-01-13 11:04 UTC, mjbloemer commented on gettsim/parameters/eink_st_abzuege.yaml
>      reference:
```suggestion
  1975-01-01:
    reference: G. v. 05.08.1974 BGBl. I S. 1769.
```

2022-01-14 06:34 UTC, ChristianZimpelmann approved these changes
Thanks for finding this @mjbloemer! 

Would it make sense to also mention the number of the bullet point and/or the exact page where the respective change is mentioned? I had a hard time looking for it, especially as the scanned law is not searchable.  

Otherwise, you can merge from my perspective after Maximilan's suggestion is committed.

2022-01-18 08:14 UTC, ChristianZimpelmann commented
@lillyfischer, would you like to make the change suggested by @mjbloemer and edit `changes.rst`?

Then we can merge. @mjbloemer convinced me that we should only mention the first page of the law (as it is currently done).

2022-01-19 16:24 UTC, Eric-Sommer commented
>  @mjbloemer convinced me that we should only mention the first page of the law (as it is currently done).


I agree. Usually, changes are not that hard to spot. In this case, the reform was issued by writing down the complete law in the changed form.

2022-01-25 09:18 UTC, mjbloemer approved these changes

2022-01-25 10:32 UTC, merged

2022-01-25 10:32 UTC, hmgaudecker commented
Very nice PR, thank you!