Documentation for Vermögensbegriff
iza-institute-of-labor-economics/gettsim pull request #416
Opened 2022-09-05 11:30 UTC by LauraGergeleit

### What problem do you want to solve?
Referring to #326, the variable `vermögen_hh` was changed into `vermögen_bedürft_hh` (Vermögen für Bedürftigkeitsprüfungen). In order to understand which assets are not counted towards Vermögen for each relevant transfer, a table was created, which shall be added to the documentation of GETTSIM, as asked [here](https://github.com/iza-institute-of-labor-economics/gettsim/issues/326#issuecomment-1158598062).

2022-09-06 06:41 UTC, ChristianZimpelmann requested changes
Thanks!

- I made a few comments (let me know if you think some change doesn't make sense).
- Can we put a link to this page in the table in `input_variables`, where `vermögen_bedürft_hh` is described?

2022-09-06 06:41 UTC, ChristianZimpelmann commented on docs/gettsim_objects/means_testing.rst
> +   HS = hardship case
HC?

Also explain a bit what this mean.

2022-09-06 06:41 UTC, ChristianZimpelmann commented on docs/gettsim_objects/means_testing.rst
> +| The table below gives an overview of all tangible and intangible assets which are deducted from the overall assets of a household when performing means testing for the respective transfer.
```suggestion
| The table below gives an overview of all tangible and intangible assets which are considered when performing means for several transfers. A cross indicates that the asset class is not considered and, hence, deducted from the overall assets of a household.
```

2022-09-06 06:41 UTC, ChristianZimpelmann commented on docs/gettsim_objects/means_testing.rst
> +Assets for means testing
```suggestion
Assets considered for means testing for various transfers
```

2022-09-06 06:41 UTC, ChristianZimpelmann commented on docs/gettsim_objects/means_testing.rst
> +|| owner-occupied house/apartment of            ||   x    ||   x    ||   x    ||   x    |
Make sure that the descriptions all start with a capital letter and don't have any capital letters thereafter.

2022-09-06 06:41 UTC, ChristianZimpelmann commented on docs/gettsim_objects/means_testing.rst
> +|| or Establishment of a household              ||        ||        ||        ||        |
Make sure that the descriptions all start with a capital letter and don't have any capital letters thereafter.

2022-09-06 06:41 UTC, ChristianZimpelmann commented on docs/gettsim_objects/means_testing.rst
> +    Here you can check out the legal bases for the definition of assets for each transfer.
```suggestion
    See the following links for legal bases for the definition of assets for each transfer.
```

2022-09-06 06:41 UTC, ChristianZimpelmann commented on docs/gettsim_objects/means_testing.rst
> +| This documentation shall help to understand the composition of the :ref:`basic input variable <input_variables>` 'vermögen_bedürft_hh'.
```suggestion
| This documentation shall help to understand the composition of the :ref:`basic input variable <input_variables>` 'vermögen_bedürft_hh'. Despite small differences over the transfers we decided, for now, to require only one wealth variable as input and use it for all transfers.
```

2022-09-06 09:18 UTC, LauraGergeleit commented
>     * I made a few comments (let me know if you think some change doesn't make sense).
> 
>     * Can we put a link to this page in the table in `input_variables`, where `vermögen_bedürft_hh` is described?
Thanks for the comments, I incorporated them and I was also able to add a reference to this page in the basic input variable table.

2022-09-09 04:55 UTC, ChristianZimpelmann approved these changes
Well done!

2022-09-09 04:55 UTC, merged